[workspace]
members = [
    "crates/dsfb",
    "crates/dsfb-fusion-bench",
    "crates/dsfb-starship",
    "crates/dsfb-hret",
    "crates/dsfb-ddmf",
    "crates/dsfb-add",
]
default-members = ["crates/dsfb"]
resolver = "2"
